name: Windows Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure
        run: >
          cmake -B build
          -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=x64-mingw-static

      - name: Build
        run: cmake --build build --config Release

      - name: Create installer
        run: |
          copy build\Release\r-type_client.exe installer\
          copy build\Release\r-type_server.exe installer\
          makensis installer\installer.nsi

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: R-Type-Setup.exe
